### ISSUE TITLE
On screen keyboard is out of place

### ISSUE THREAD

**Issue by pitsi** [TPX01/quartz#1]
As seen on my screenshot, the on screen keyboard has some weird vertical misplacement. 

![screenshot000](https://cloud.githubusercontent.com/assets/5880037/25141854/90147e6c-246d-11e7-983f-abcc4a5fc4ff.png)

The screenshot is from kodi 16.1 on openelec 7.0.3, running on a raspberry pi zero. I have no other way to reproduce the bug on some other system. However, on my pc running kodi 17.1 (on debian testing x64), the krypton version of the skin places the on screen keyboard in the right place

![screenshot000](https://cloud.githubusercontent.com/assets/5880037/25142011/1cbc59ca-246e-11e7-9d39-4fca8d94e274.png)

**Comment by pitsi** [comment]
Just a minor update. On version 5.2.2 the on screen keyboard appears correctly alligned.

![screenshot000](https://cloud.githubusercontent.com/assets/5880037/25142906/3c2923c6-2471-11e7-9414-029485f1941b.png)

And it does align properly on 5.3 when kodi is switched to the english locale (I use greek locale as seen on the first screenshot)

![screenshot000](https://cloud.githubusercontent.com/assets/5880037/25143159/137958dc-2472-11e7-954a-15de4baacd31.png)

**Comment by pitsi** [comment]
---edit---
I made a huge mistake. I closed the bug thinking it was fixed, but I was at 5.2.2 when I checked. I am reopening it now.

**Comment by ghost** [comment]
Issue still exist? Can you see if it also occurs in Jarvis? In that way I can try to find a fix for both.

**Comment by pitsi** [comment]
Last time I checked it, the issue was still present, even with the english locale. Bad thing is I was "forced" to upgrade to kodi 17.x series (a week or so ago) due to the subtitles security bug*, since the kodi devs refused to patch 16.x or earlier releases. So I have no way to check the bug now, at least on my systems. I will check it on my friends' installations that are still on 16.x, before upgrading them.

And no, the bug does not apply to ~~jarvis~~ krypton as I remember. I will post screenshots later on the day if needed. 

* http://blog.checkpoint.com/2017/05/23/hacked-in-translation/

**Comment by pitsi** [comment]
To add to the above, the issue does not appear on krypton. 
In the screenshots above, jarvis is where the text box has rounded corners and krypton is the one which the text box has pointy corners. Here is a fresh screenshot though

![screenshot000](https://user-images.githubusercontent.com/5880037/28123104-c4150c88-6728-11e7-8164-9fd08ad16d91.png)

**Comment by pitsi** [comment]
So, here is the screenshot that shows that the problem persists

![screenshot000](https://user-images.githubusercontent.com/5880037/28607512-e9d8df14-71e4-11e7-94ed-a812736b064b.png)

 Kodi 16.1, using quartz 5.3, on windows 7 x64

The bigger rectangle on the bottom right corner is from the menu below the on screen keyboard, ignore it.
